# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches:
      - release/**
  pull_request:
  workflow_run:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze
        
      - name: Build project from source
        run: mkdir D:\a\file_cleaner\file_cleaner\build && dart compile exe D:\a\file_cleaner\file_cleaner\bin\file_cleaner.dart -o D:\a\file_cleaner\file_cleaner\build\file_cleaner_DEV.exe
        
      - name: Archive built executable
        uses: actions/upload-artifact@v2
        with:
          name: file_cleaner Windows
          path: D:\a\file_cleaner\file_cleaner\build
        
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze
        
      - name: Build project from source
        run: mkdir /Users/runner/work/file_cleaner/file_cleaner/build && dart compile exe /Users/runner/work/file_cleaner/file_cleaner/bin/file_cleaner.dart -o /Users/runner/work/file_cleaner/file_cleaner/build/file_cleaner_DEV
        
      - name: Archive built executable
        uses: actions/upload-artifact@v2
        with:
          name: file_cleaner macOS
          path: build
        
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
        
      - name: Analyze project source
        run: dart analyze
        
      - name: Build project from source
        run: mkdir /home/runner/work/file_cleaner/file_cleaner/build && dart compile exe /home/runner/work/file_cleaner/file_cleaner/bin/file_cleaner.dart -o /home/runner/work/file_cleaner/file_cleaner/build/file_cleaner_DEV
        
      - name: Archive built executable
        uses: actions/upload-artifact@v2
        with:
          name: file_cleaner Linux
          path: build
